import { Course } from "@/types/Course";

export const ai: Course = {
  title: {
    fa: "هوش مصنوعی",
    en: "ai",
  },
  callout: "کیفیت صدا پایین است. قبل از پخش کمی صدا را کم کنید!",
  sources: [
    {
      id: "1-slide",
      title: "اسلاید فصل اول",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/1-slide.pdf",
    },
    {
      id: "2-slide",
      title: "اسلاید فصل دوم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/2-slide.pdf",
    },
    {
      id: "3-slide",
      title: "اسلاید فصل سوم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/3-slide.pdf",
    },
    {
      id: "4-slide",
      title: "اسلاید فصل چهارم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/4-slide.pdf",
    },
    {
      id: "5-slide",
      title: "اسلاید فصل پنجم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/5-slide.pdf",
    },
    {
      id: "6-slide",
      title: "اسلاید فصل ششم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/6-slide.pdf",
    },
    {
      id: "7-slide",
      title: "اسلاید فصل هفتم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/7-slide.pdf",
    },
    {
      id: "8-slide",
      title: "اسلاید فصل هشتم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/8-slide.pdf",
    },
    {
      id: "9-slide",
      title: "اسلاید فصل نهم",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/9-slide.pdf",
    },
    {
      id: "1",
      title: "جلسه یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/1.mp4",
    },
    {
      id: "2",
      title: "جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/2.mp4",
    },
    {
      id: "3",
      title: "جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/3.mp4",
    },
    {
      id: "4",
      title: "جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/4.mp4",
    },
    {
      id: "5",
      title: "جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/6.mp4",
    },
    {
      id: "7",
      title: "جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/7.mp4",
    },
    {
      id: "8",
      title: "جلسه هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/8.mp4",
    },
    {
      id: "9",
      title: "جلسه نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/9.mp4",
    },
    {
      id: "10",
      title: "جلسه دهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/10.mp4",
    },
    {
      id: "11",
      title: "جلسه یازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/11.mp4",
    },
    {
      id: "12",
      title: "جلسه دوازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/12.mp4",
    },
    {
      id: "13",
      title: "جلسه سیزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/13.mp4",
    },
    {
      id: "14",
      title: "جلسه چهاردهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/14.mp4",
    },
    {
      id: "15",
      title: "جلسه پانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/15.mp4",
    },
    {
      id: "16",
      title: "جلسه شانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/16.mp4",
    },
    {
      id: "17",
      title: "جلسه هفدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/17.mp4",
    },
    {
      id: "18",
      title: "جلسه هجدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/18.mp4",
    },
    {
      id: "19",
      title: "جلسه نوزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/19.mp4",
    },
    {
      id: "20",
      title: "جلسه بیستم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/20.mp4",
    },
    {
      id: "21",
      title: "جلسه بیست و یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/21.mp4",
    },
    {
      id: "22",
      title: "جلسه بیست و دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/22.mp4",
    },
    {
      id: "23",
      title: "جلسه بیست و سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/23.mp4",
    },
    {
      id: "24",
      title: "جلسه بیست و چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/ai/24.mp4",
    },
  ],
};
