import { Course } from "@/types/Course";

export const algorithmDesign: Course = {
  title: {
    fa: "طراحی الگوریتم",
    en: "algorithm-design",
  },
  sources: [
    {
      id: "1-1",
      title: "جلسه یکم بخش اول - Mathematics",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/1-1.mp4",
    },
    {
      id: "1-2",
      title: "جلسه یکم بخش اول - Mathematics",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/1-2.mp4",
    },
    {
      id: "2-1",
      title: "جلسه دوم بخش اول - Mathematics",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/2-1.mp4",
    },
    {
      id: "2-2",
      title: "جلسه دوم بخش دوم - Mathematics",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/2-2.mp4",
    },
    {
      id: "3-1",
      title: "جلسه سوم بخش اول - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/3-1.mov",
    },
    {
      id: "3-2",
      title: "جلسه سوم بخش دوم - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/3-2.mov",
    },
    {
      id: "3-3",
      title: "جلسه سوم بخش سوم - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/3-3.mov",
    },
    {
      id: "4-1",
      title: "جلسه چهارم بخش اول - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/4-1.mov",
    },
    {
      id: "4-2",
      title: "جلسه چهارم بخش دوم - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/4-2.mov",
    },
    {
      id: "4-3",
      title: "جلسه چهارم بخش سوم - D&C",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/4-3.mov",
    },
    {
      id: "5-1",
      title: "جلسه پنجم بخش اول - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/5-1.mov",
    },
    {
      id: "5-2",
      title: "جلسه پنجم بخش دوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/5-2.mov",
    },
    {
      id: "5-3",
      title: "جلسه پنجم بخش سوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/5-3.mov",
    },
    {
      id: "6-1",
      title: "جلسه ششم بخش اول - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/6-1.mov",
    },
    {
      id: "6-2",
      title: "جلسه ششم بخش دوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/6-2.mov",
    },
    {
      id: "6-3",
      title: "جلسه ششم بخش سوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/6-3.mov",
    },
    {
      id: "7-1",
      title: "جلسه هفتم بخش اول - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/7-1.mov",
    },
    {
      id: "7-2",
      title: "جلسه هفتم بخش دوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/7-2.mov",
    },
    {
      id: "7-3",
      title: "جلسه هفتم بخش سوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/7-3.mp4",
    },
    {
      id: "8-1",
      title: "جلسه هشتم بخش اول - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/8-1.mp4",
    },
    {
      id: "8-2",
      title: "جلسه هشتم بخش دوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/8-2.mp4",
    },
    {
      id: "8-3",
      title: "جلسه هشتم بخش سوم - DP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/8-3.mp4",
    },
    {
      id: "9-1",
      title: "جلسه نهم بخش اول - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/9-1.mp4",
    },
    {
      id: "9-2",
      title: "جلسه نهم بخش دوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/9-2.mp4",
    },
    {
      id: "9-3",
      title: "جلسه نهم بخش سوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/9-3.mp4",
    },
    {
      id: "10-1",
      title: "جلسه دهم بخش اول - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/10-1.mp4",
    },
    {
      id: "10-2",
      title: "جلسه دهم بخش دوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/10-2.mp4",
    },
    {
      id: "10-3",
      title: "جلسه دهم بخش سوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/10-3.mp4",
    },
    {
      id: "11-1",
      title: "جلسه یازدهم بخش اول - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/11-1.mp4",
    },
    {
      id: "11-2",
      title: "جلسه یازدهم بخش دوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/11-2.mp4",
    },
    {
      id: "11-3",
      title: "جلسه یازدهم بخش سوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/11-3.mp4",
    },
    {
      id: "12-1",
      title: "جلسه دوازدهم بخش اول - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/12-1.mp4",
    },
    {
      id: "12-2",
      title: "جلسه دوازدهم بخش دوم - Greedy",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/12-2.mp4",
    },
    {
      id: "13-1",
      title: "جلسه سیزدهم بخش اول - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/13-1.mp4",
    },
    {
      id: "13-2",
      title: "جلسه سیزدهم بخش دوم - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/13-2.mp4",
    },
    {
      id: "13-3",
      title: "جلسه سیزدهم بخش سوم - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/13-3.mp4",
    },
    {
      id: "14-1",
      title: "جلسه چهاردهم بخش اول - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/14-1.mp4",
    },
    {
      id: "14-2",
      title: "جلسه چهاردهم بخش دوم - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/14-2.mp4",
    },
    {
      id: "14-3",
      title: "جلسه چهاردهم بخش سوم - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/14-3.mp4",
    },
    {
      id: "15-1",
      title: "جلسه پانزدهم بخش اول - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/15-1.mp4",
    },
    {
      id: "15-2",
      title: "جلسه پانزدهم بخش دوم - BT",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/15-2.mp4",
    },
    {
      id: "16-1",
      title: "جلسه شانزدهم بخش اول - NP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/16-1.mp4",
    },
    {
      id: "16-2",
      title: "جلسه شانزدهم بخش دوم - NP",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/16-2.mp4",
    },
    {
      id: "17-1",
      title: "جلسه هفدهم بخش اول - CLRS",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/17-1.mp4",
    },
    {
      id: "17-2",
      title: "جلسه هفدهم بخش دوم - CLRS",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/algorithm-design/17-2.mp4",
    },
  ],
};
