import { Course } from "@/types/Course";

export const compiler: Course = {
  title: {
    fa: "اصول طراحی کامپایلر",
    en: "compiler",
  },
  sources: [
    {
      id: "1",
      title: "جلسه یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/1.mp4",
    },
    {
      id: "2",
      title: "جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/2.mp4",
    },
    {
      id: "3",
      title: "جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/3.mp4",
    },
    {
      id: "4",
      title: "جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/4.mp4",
    },
    {
      id: "5",
      title: "جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/6.mp4",
    },
    {
      id: "7",
      title: "جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/7.mp4",
    },
    {
      id: "8",
      title: "جلسه هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/8.mp4",
    },
    {
      id: "9",
      title: "جلسه نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/9.mp4",
    },
    {
      id: "10",
      title: "جلسه دهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/10.mp4",
    },
    {
      id: "11",
      title: "جلسه یازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/11.mp4",
    },
    {
      id: "12",
      title: "جلسه دوازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/12.mp4",
    },
    {
      id: "13",
      title: "جلسه سیزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/13.mp4",
    },
    {
      id: "14",
      title: "جلسه چهاردهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/14.mp4",
    },
    {
      id: "15",
      title: "جلسه پانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/15.mp4",
    },
    {
      id: "16",
      title: "جلسه شانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/16.mp4",
    },
    {
      id: "17",
      title: "جلسه هفدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/17.mp4",
    },
    {
      id: "18",
      title: "جلسه هجدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/18.mp4",
    },
    {
      id: "19",
      title: "جلسه نوزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/19.mp4",
    },
    {
      id: "20",
      title: "جلسه بیستم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/20.mp4",
    },
    {
      id: "21",
      title: "جلسه بیست و یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/21.mp4",
    },
    {
      id: "22",
      title: "جلسه بیست و دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/22.mp4",
    },
    {
      id: "23",
      title: "جلسه بیست و سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/23.mp4",
    },
    {
      id: "24",
      title: "جلسه بیست و چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/24.mp4",
    },
    {
      id: "25",
      title: "جلسه بیست و پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/25.mp4",
    },
    {
      id: "26",
      title: "جلسه بیست و ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/26.mp4",
    },
    {
      id: "27",
      title: "جلسه بیست و هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/27.mp4",
    },
    {
      id: "28",
      title: "جلسه بیست و هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/28.mp4",
    },
    {
      id: "29",
      title: "جلسه بیست و نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/compiler/29.mp4",
    },
  ],
};
