import { Course } from "@/types/Course";

export const differentialEquations: Course = {
  title: {
    fa: "معادلات دیفرانسیل",
    en: "differential-equations",
  },
  sources: [
    {
      id: "0-1",
      title: "فصل پیشنیاز: اعداد مختلط بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/0-1.mp4",
    },
    {
      id: "0-2",
      title: "فصل پیشنیاز: اعداد مختلط بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/0-2.mp4",
    },
    {
      id: "0-3",
      title: "فصل پیشنیاز: اعداد مختلط بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/0-3.mp4",
    },
    {
      id: "0-4",
      title: "فصل پیشنیاز: اعداد مختلط بخش چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/0-4.mp4",
    },
    {
      id: "1-1",
      title: "فصل اول جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-1.mp4",
    },
    {
      id: "1-2",
      title: "فصل اول جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-2.mp4",
    },
    {
      id: "1-3",
      title: "فصل اول جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-3.mp4",
    },
    {
      id: "1-4",
      title: "فصل اول جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-4.mp4",
    },
    {
      id: "1-5",
      title: "فصل اول جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-5.mp4",
    },
    {
      id: "1-6",
      title: "فصل اول جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-6.mp4",
    },
    {
      id: "1-7",
      title: "فصل اول جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/1-7.mp4",
    },
    {
      id: "2-1",
      title: "فصل دوم جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-1.mp4",
    },
    {
      id: "2-2",
      title: "فصل دوم جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-2.mp4",
    },
    {
      id: "2-3",
      title: "فصل دوم جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-3.mp4",
    },
    {
      id: "2-4",
      title: "فصل دوم جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-4.mp4",
    },
    {
      id: "2-5",
      title: "فصل دوم جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-5.mp4",
    },
    {
      id: "2-6",
      title: "فصل دوم جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-6.mp4",
    },
    {
      id: "2-7",
      title: "فصل دوم جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/2-7.mp4",
    },
    {
      id: "3-1",
      title: "فصل سوم جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/3-1.mp4",
    },
    {
      id: "4-1",
      title: "فصل چهارم: جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/4-1.mp4",
    },
    {
      id: "4-2",
      title: "فصل چهارم جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/4-2.mp4",
    },
    {
      id: "4-3",
      title: "فصل چهارم جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/4-3.mp4",
    },
    {
      id: "6-1",
      title: "فصل ششم جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/6-1.mp4",
    },
    {
      id: "5-1",
      title: "فصل پنجم جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-1.mp4",
    },
    {
      id: "5-2",
      title: "فصل پنجم جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-2.mp4",
    },
    {
      id: "5-3-1",
      title: "فصل پنجم جلسه سوم بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-3-1.mp4",
    },
    {
      id: "5-3-2",
      title: "فصل پنجم جلسه سوم بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-3-2.mp4",
    },
    {
      id: "5-4",
      title: "فصل پنجم جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-4.mp4",
    },
    {
      id: "5-5",
      title: "فصل پنجم جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-5.mp4",
    },
    {
      id: "5-6",
      title: "فصل پنجم جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/differential-equations/5-6.mp4",
    },
  ],
};
