import { Course } from "@/types/Course";

export const electricElectronicCircuits: Course = {
  title: {
    fa: "مدارهای الکتریکی و الکترونیکی",
    en: "electric-electronic-circuits",
  },
  sources: [
    {
      id: "1",
      title: "جلسه یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/1.mp4",
    },
    {
      id: "2",
      title: "جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/2.mp4",
    },
    {
      id: "3-1",
      title: "جلسه سوم بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/3-1.mp4",
    },
    {
      id: "3-2",
      title: "جلسه سوم بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/3-2.mp4",
    },
    {
      id: "4-2",
      title: "جلسه چهارم بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/4-2.mp4",
    },
    {
      id: "5",
      title: "جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/6.mp4",
    },
    {
      id: "8",
      title: "جلسه هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/8.mp4",
    },
    {
      id: "9",
      title: "جلسه نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/9.mp4",
    },
    {
      id: "10",
      title: "جلسه دهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/10.mp4",
    },
    {
      id: "11",
      title: "جلسه یازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/11.mp4",
    },
    {
      id: "12",
      title: "جلسه دوازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/12.mp4",
    },
    {
      id: "13",
      title: "جلسه سیزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/13.mp4",
    },
    {
      id: "14",
      title: "جلسه چهاردهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/14.mp4",
    },
    {
      id: "15-1",
      title: "جلسه پانزدهم بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/15-1.mp4",
    },
    {
      id: "15",
      title: "جلسه پانزدهم بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/15-2.mp4",
    },
    {
      id: "16",
      title: "جلسه شانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/16.mp4",
    },
    {
      id: "17",
      title: "جلسه هفدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/17.mp4",
    },
    {
      id: "18",
      title: "جلسه هجدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/18.mp4",
    },
    {
      id: "19",
      title: "جلسه نوزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/19.mp4",
    },
    {
      id: "20",
      title: "جلسه بیستم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/20.mp4",
    },
    {
      id: "21",
      title: "جلسه بیست و یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/21.mp4",
    },
    {
      id: "22",
      title: "جلسه بیست و دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/22.mp4",
    },
    {
      id: "23",
      title: "جلسه بیست و سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/23.mp4",
    },
    {
      id: "24",
      title: "جلسه بیست و چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/24.mp4",
    },
    {
      id: "25-1",
      title: "جلسه بیست و پنجم بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/25-1.mp4",
    },
    {
      id: "25-2",
      title: "جلسه بیست و پنجم بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/25-2.mp4",
    },
    {
      id: "26",
      title: "جلسه بیست و ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/26.mp4",
    },
    {
      id: "27",
      title: "جلسه بیست و هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/27.mp4",
    },
    {
      id: "28",
      title: "جلسه بیست و هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/28.mp4",
    },
    {
      id: "29",
      title: "جلسه بیست و نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/electric-electronic-circuits/29.mp4",
    },
  ],
};
