import { Course } from "@/types/Course";

export const linearAlgebra: Course = {
  title: {
    fa: "جبر خطی",
    en: "linear-algebra",
  },
  callout: "کیفیت صدا پایین است. قبل از پخش کمی صدا را کم کنید!",
  sources: [
    {
      id: "0-note",
      title: "اسلاید چرا جبر خطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/0-slide.pdf",
    },
    {
      id: "1-note",
      title: "اسلاید دستگاه معادلات خطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/1-slide.pdf",
    },
    {
      id: "2-note",
      title: "اسلاید echelon form",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/2-slide.pdf",
    },
    {
      id: "3-note",
      title: "اسلاید echelon form 2",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/3-slide.pdf",
    },
    {
      id: "4-note",
      title: "اسلاید بخش بردار",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/4-slide.pdf",
    },
    {
      id: "5-note",
      title: "اسلاید معادله ماتریسی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/5-slide.pdf",
    },
    {
      id: "6-note",
      title: "اسلاید بخش 1.5",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/6-slide.pdf",
    },
    {
      id: "7-note",
      title: "اسلاید بخش 1-2",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/7-slide.pdf",
    },
    {
      id: "8-note",
      title: "اسلاید بخش 2-2",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/8-slide.pdf",
    },
    {
      id: "9-note",
      title: "اسلاید بخش 3-2",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/9-slide.pdf",
    },
    {
      id: "10-note",
      title: "اسلاید بخش 1-3",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/10-slide.pdf",
    },
    {
      id: "11-note",
      title: "اسلاید بخش 2-3",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/11-slide.pdf",
    },
    {
      id: "12-note",
      title: "اسلاید بخش 3-3",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/12-slide.pdf",
    },
    {
      id: "13-note",
      title: "اسلاید بخش 1-4",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/13-slide.pdf",
    },
    {
      id: "14-note",
      title: "اسلاید بخش 2-4",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/14-slide.pdf",
    },
    {
      id: "15-note",
      title: "اسلاید بخش 3-4",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/15-slide.pdf",
    },
    {
      id: "16-note",
      title: "اسلاید بخش 6-4",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/16-slide.pdf",
    },
    {
      id: "17-note",
      title: "اسلاید بخش 1-5",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/17-slide.pdf",
    },
    {
      id: "18-note",
      title: "اسلاید بخش 2-5",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/18-slide.pdf",
    },
    {
      id: "19-note",
      title: "اسلاید بخش 3-5",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/19-slide.pdf",
    },
    {
      id: "20-note",
      title: "اسلاید بخش 1-6",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/20-slide.pdf",
    },
    {
      id: "21-note",
      title: "اسلاید بخش 2-6",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/21-slide.pdf",
    },
    {
      id: "22-note",
      title: "اسلاید بخش 4-6",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/22-slide.pdf",
    },
    {
      id: "23-note",
      title: "اسلاید بخش 5-6",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/23-slide.pdf",
    },
    {
      id: "24-note",
      title: "اسلاید بخش 1-7",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/24-slide.pdf",
    },
    {
      id: "25-note",
      title: "اسلاید SVD",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/25-slide.pdf",
    },
    {
      id: "1",
      title: "جلسه یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/1.mp4",
    },
    {
      id: "2",
      title: "جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/2.mp4",
    },
    {
      id: "3",
      title: "جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/3.mp4",
    },
    {
      id: "4",
      title: "جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/4.mp4",
    },
    {
      id: "5",
      title: "جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/6.mp4",
    },
    {
      id: "7",
      title: "جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/7.mp4",
    },
    {
      id: "8",
      title: "جلسه هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/8.mp4",
    },
    {
      id: "9",
      title: "جلسه نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/9.mp4",
    },
    {
      id: "10",
      title: "جلسه دهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/10.mp4",
    },
    {
      id: "11",
      title: "جلسه یازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/11.mp4",
    },
    {
      id: "12",
      title: "جلسه دوازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/12.mp4",
    },
    {
      id: "13",
      title: "جلسه سیزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/13.mp4",
    },
    {
      id: "14",
      title: "جلسه چهاردهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/14.mp4",
    },
    {
      id: "15",
      title: "جلسه پانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/15.mp4",
    },
    {
      id: "16",
      title: "جلسه شانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/16.mp4",
    },
    {
      id: "18",
      title: "جلسه هجدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/18.mp4",
    },
    {
      id: "19",
      title: "جلسه نوزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/19.mp4",
    },
    {
      id: "20",
      title: "جلسه بیستم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/20.mp4",
    },
    {
      id: "23",
      title: "جلسه بیست و سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/23.mp4",
    },
    {
      id: "24",
      title: "جلسه بیست و چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/24.mp4",
    },
    {
      id: "25",
      title: "جلسه بیست و پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/25.mp4",
    },
    {
      id: "26",
      title: "جلسه بیست و ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/26.mp4",
    },
    {
      id: "27",
      title: "جلسه بیست و هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/27.mp4",
    },
    {
      id: "28",
      title: "جلسه بیست و هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/linear-algebra/28.mp4",
    },
  ],
};
