import { Course } from "@/types/Course";

export const os: Course = {
  title: {
    fa: "سیستم های عامل",
    en: "os",
  },
  sources: [
    {
      id: "1",
      title: "جلسه یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/1.mp4",
    },
    {
      id: "2",
      title: "جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/2.mp4",
    },
    {
      id: "3",
      title: "جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/3.mp4",
    },
    {
      id: "4",
      title: "جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/4.mp4",
    },
    {
      id: "5",
      title: "جلسه پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/6.mp4",
    },
    {
      id: "7",
      title: "جلسه هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/7.mp4",
    },
    {
      id: "8",
      title: "جلسه هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/8.mp4",
    },
    {
      id: "9",
      title: "جلسه نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/9.mp4",
    },
    {
      id: "10",
      title: "جلسه دهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/10.mp4",
    },
    {
      id: "11",
      title: "جلسه یازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/11.mp4",
    },
    {
      id: "12",
      title: "جلسه دوازدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/12.mp4",
    },
    {
      id: "13",
      title: "جلسه سیزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/13.mp4",
    },
    {
      id: "14",
      title: "جلسه چهاردهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/14.mp4",
    },
    {
      id: "15",
      title: "جلسه پانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/15.mp4",
    },
    {
      id: "16",
      title: "جلسه شانزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/16.mp4",
    },
    {
      id: "17",
      title: "جلسه هفدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/17.mp4",
    },
    {
      id: "18",
      title: "جلسه هجدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/18.mp4",
    },
    {
      id: "19",
      title: "جلسه نوزدهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/19.mp4",
    },
    {
      id: "20",
      title: "جلسه بیستم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/20.mp4",
    },
    {
      id: "21",
      title: "جلسه بیست و یکم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/21.mp4",
    },
    {
      id: "22",
      title: "جلسه بیست و دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/22.mp4",
    },
    {
      id: "23",
      title: "جلسه بیست و سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/23.mp4",
    },
    {
      id: "24",
      title: "جلسه بیست و چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/24.mp4",
    },
    {
      id: "25",
      title: "جلسه بیست و پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/25.mp4",
    },
    {
      id: "26",
      title: "جلسه بیست و ششم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/26.mp4",
    },
    {
      id: "27",
      title: "جلسه بیست و هفتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/27.mp4",
    },
    {
      id: "28",
      title: "جلسه بیست و هشتم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/28.mp4",
    },
    {
      id: "29",
      title: "جلسه بیست و نهم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/os/29.mp4",
    },
  ],
};
