import { Course } from "@/types/Course";

export const physics2: Course = {
  title: {
    fa: "فیزیک ۲",
    en: "physics-2",
  },
  sources: [
    {
      id: "1",
      title: "جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/1.mp4",
    },
    {
      id: "2",
      title: "نیروی الکتریکی - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/2.m4v",
    },
    {
      id: "3",
      title: "نیروی الکتریکی - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/3.m4v",
    },
    {
      id: "4",
      title: "میدان الکتریکی - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/4.mp4",
    },
    {
      id: "5",
      title: "میدان الکتریکی - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/5.wmv",
    },
    {
      id: "6",
      title: "قانون گاوس - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/6.mp4",
    },
    {
      id: "7",
      title: "قانون گاوس - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/7.mp4",
    },
    {
      id: "8",
      title: "قانون گاوس - بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/8.m4v",
    },
    {
      id: "9",
      title: "پتانسیل الکتریکی - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/9.mp4",
    },
    {
      id: "10",
      title: "پتانسیل الکتریکی - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/10.m4v",
    },
    {
      id: "11",
      title: "پتانسیل الکتریکی - بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/11.m4v",
    },
    {
      id: "12",
      title: "خازنو دی الکتریک - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/12.m4v",
    },
    {
      id: "13",
      title: "خازنو دی الکتریک - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/13.m4v",
    },
    {
      id: "14",
      title: "خازنو دی الکتریک - بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/14.m4v",
    },
    {
      id: "15",
      title: "خازنو دی الکتریک - بخش چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/15.mp4",
    },
    {
      id: "16",
      title: "خازنو دی الکتریک - بخش پنجم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/16.m4v",
    },
    {
      id: "17",
      title: "جریان الکتریکی و مقاومت - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/17.m4v",
    },
    {
      id: "18",
      title: "جریان الکتریکی و مقاومت - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/18.m4v",
    },
    {
      id: "19",
      title: "جریان الکتریکی و مقاومت - بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/19.m4v",
    },
    {
      id: "20",
      title: "نیروی محرکه الکتریکی و مدار - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/20.m4v",
    },
    {
      id: "21",
      title: "نیروی محرکه الکتریکی و مدار - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/21.m4v",
    },
    {
      id: "22",
      title: "نیروی مغناطیسی - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/22.m4v",
    },
    {
      id: "23",
      title: "نیروی مغناطیسی - بخش دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/23.m4v",
    },
    {
      id: "24",
      title: "نیروی مغناطیسی - بخش سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/24.m4v",
    },
    {
      id: "25",
      title: "ایجاد میدان مغناطیسی قانون بیوساوار",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/25.m4v",
    },
    {
      id: "26",
      title: "ایجاد میدان مغناطیسی قانون آمپر - بخش اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/26.m4v",
    },
    {
      id: "27",
      title: "ایجاد میدان مغناطیسی قانون آمپر - بخش دوم ",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/27.m4v",
    },
    {
      id: "28",
      title: "نیروی محرکه القایی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/28.m4v",
    },
    {
      id: "29",
      title: "قانون القای فاراده",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/29.m4v",
    },
    {
      id: "30",
      title: "خودالقایی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/30.m4v",
    },
    {
      id: "31",
      title: "مدار RL و LC",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/physics-2/31.m4v",
    },
  ],
};
