import { Course } from "@/types/Course";

export const probability: Course = {
  title: {
    fa: "آمار و احتمالات مهندسی",
    en: "probability",
  },
  sources: [
    {
      id: "1-note",
      title: "جزوه آمار و احتمال مهندسی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/1-note.pdf",
    },
    {
      id: "1",
      title: "جلسه ۱: مقدمه و مروری بر نظریه مجموعه‌ها",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/1.mp4",
    },
    {
      id: "2",
      title: "جلسه ۲: تعریف اصولی از احتمال و مروری بر آنالیز ترکیبی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/2.mp4",
    },
    {
      id: "3",
      title: "جلسه ۳: ادامه آنالیز ترکیبی و تعریف احتمال شرطی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/3.mp4",
    },
    {
      id: "4",
      title: "جلسه ۴: ادامه احتمال شرطی، قضیه احتمال کل و قضیه بیز",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/4.mp4",
    },
    {
      id: "5",
      title: "جلسه ۵: آزمایش‌های تکراری",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ۶: قضیه پواسون",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/6.mp4",
    },
    {
      id: "7",
      title: "جلسه ۷: حل تمرین‌های مباحث آنالیز ترکیبی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/7.mp4",
    },
    {
      id: "8",
      title: "جلسه ۸: حل تمرین‌های مباحث احتمال شرطی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/8.mp4",
    },
    {
      id: "9",
      title: "جلسه ۹: متغیرهای تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/9.mp4",
    },
    {
      id: "10",
      title: "جلسه ۱۰: تابع توزیع انباشته",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/10.mp4",
    },
    {
      id: "11",
      title: "جلسه ۱۱: ادامه تابع توزیع انباشته ",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/11.mp4",
    },
    {
      id: "12",
      title: "جلسه ۱۲: آشنایی با ابزارهای اکسل",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/12.mp4",
    },
    {
      id: "13",
      title: "جلسه ۱۳: تابع چگالی احتمال",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/13.mp4",
    },
    {
      id: "14",
      title: "جلسه ۱۴: میانگین و واریانس",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/14.mp4",
    },
    {
      id: "15",
      title: "جلسه ۱۵: آشنایی با اکتاو/متلب",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/15.mp4",
    },
    {
      id: "16",
      title: "جلسه ۱۶: خواص امید ریاضی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/16.mp4",
    },
    {
      id: "17",
      title: "جلسه ۱۷: نامساوی مارکف و بینه",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/17.mp4",
    },
    {
      id: "18",
      title: "جلسه ۱۸: واریانس",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/18.mp4",
    },
    {
      id: "19",
      title: "جلسه ۱۹: توزیع یکنواخت و توزیع گوسی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/19.mp4",
    },
    {
      id: "20",
      title: "جلسه ۲۰: توزیع نمایی، رایلی و کوشی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/20.mp4",
    },
    {
      id: "21",
      title: "جلسه ۲۱: توزیع دوجمله‌ای، توزیع هندسی و تابعی از یک متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/21.mp4",
    },
    {
      id: "22",
      title: "جلسه ۲۲: ادامه تابعی از یک متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/22.mp4",
    },
    {
      id: "23",
      title: "جلسه ۲۳: قضیه اساسی امید ریاضی، تعریف گشتاور یک متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/23.mp4",
    },
    {
      id: "24",
      title: "جلسه ۲۴: تابع مولد گشتاور",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/24.mp4",
    },
    {
      id: "25",
      title: "جلسه ۲۵: تابع مشخصه",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/25.mp4",
    },
    {
      id: "26",
      title: "جلسه ۲۶: دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/26.mp4",
    },
    {
      id: "27",
      title: "جلسه ۲۷: ادامه دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/27.mp4",
    },
    {
      id: "28",
      title: "جلسه ۲۸: تابع چگالی احتمال مشترک",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/28.mp4",
    },
    {
      id: "29",
      title: "جلسه ۲۹: متغیرهای تصادفی مستقل",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/29.mp4",
    },
    {
      id: "30",
      title: "جلسه ۳۰: کواریانس و ضریب همبستگی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/30.mp4",
    },
    {
      id: "31",
      title:
        "جلسه ۳۱: نامساوی شوارتز، تابع مولد گشتاور مشترک، تابع مشخصه مشترک",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/31.mp4",
    },
    {
      id: "32",
      title: "جلسه ۳۲: ادامه تابع مشخصه مشترک",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/32.mp4",
    },
    {
      id: "33",
      title: "جلسه ۳۳: تابعی از دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/33.mp4",
    },
    {
      id: "34",
      title: "جلسه ۳۴: ادامه تابعی از دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/34.mp4",
    },
    {
      id: "35",
      title:
        "جلسه ۳۵: ادامه تابعی از دو متغیر تصادفی، تعریف متغیرهای مشترک نرمال",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/35.mp4",
    },
    {
      id: "36",
      title: "جلسه ۳۶: توزیع شرطی (قسمت اول)",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/36.mp4",
    },
    {
      id: "37",
      title: "جلسه ۳۷: توزیع شرطی (قسمت دوم)",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/37.mp4",
    },
    {
      id: "38",
      title: "جلسه ۳۸: توزیع شرطی (قسمت سوم)",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/38.mp4",
    },
    {
      id: "39",
      title: "جلسه ۳۹: کاربردی از توزیع شرطی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/39.mp4",
    },
    {
      id: "40",
      title: "جلسه ۴۰: تخمین به‌عنوان کاربردی از توزیع شرطی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/40.mp4",
    },
    {
      id: "41",
      title:
        "جلسه ۴۱: دنباله‌ای از متغیرهای تصادفی، تابع چگالی احتمال چند‌متغیره",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/41.mp4",
    },
    {
      id: "42",
      title: "جلسه ۴۲: حل تمرین‌های مبحث دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/42.mp4",
    },
    {
      id: "43",
      title: "جلسه ۴۳: ادامه حل تمرین‌های مبحث دو متغیر تصادفی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/43.mp4",
    },
    {
      id: "44",
      title: "جلسه ۴۴: قضیه حد مرکزی",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/44.mp4",
    },
    {
      id: "45",
      title: "جلسه ۴۵: فاصله اطمینان",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/45.mp4",
    },
    {
      id: "46",
      title: "جلسه ۴۶: ادامه فاصله اطمینان + آزمون فرض",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/46.mp4",
    },
  ],
};
