export const probability = {
  title: {
    fa: "آمار و احتمالات مهندسی",
    en: "probability",
  },
  sources: [
    {
      id: "1",
      title: "جلسه ۱: مقدمه و مروری بر نظریه مجموعه‌ها",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/1.mp4",
    },
    {
      id: "2",
      title: "جلسه ۲: تعریف اصولی از احتمال و مروری بر آنالیز ترکیبی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/2.mp4",
    },
    {
      id: "3",
      title: "جلسه ۳: ادامه آنالیز ترکیبی و تعریف احتمال شرطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/3.mp4",
    },
    {
      id: "4",
      title: "جلسه ۴: ادامه احتمال شرطی، قضیه احتمال کل و قضیه بیز",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/4.mp4",
    },
    {
      id: "5",
      title: "جلسه ۵: آزمایش‌های تکراری",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/5.mp4",
    },
    {
      id: "6",
      title: "جلسه ۶: قضیه پواسون",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/6.mp4",
    },
    {
      id: "7",
      title: "جلسه ۷: حل تمرین‌های مباحث آنالیز ترکیبی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/7.mp4",
    },
    {
      id: "8",
      title: "جلسه ۸: حل تمرین‌های مباحث احتمال شرطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/8.mp4",
    },
    {
      id: "9",
      title: "جلسه ۹: متغیرهای تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/9.mp4",
    },
    {
      id: "10",
      title: "جلسه ۱۰: تابع توزیع انباشته",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/10.mp4",
    },
    {
      id: "1",
      title: "جلسه ۱۱: ادامه تابع توزیع انباشته ",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/11.mp4",
    },
    {
      id: "2",
      title: "جلسه ۱۲: آشنایی با ابزارهای اکسل",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/12.mp4",
    },
    {
      id: "3",
      title: "جلسه ۱۳: تابع چگالی احتمال",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/13.mp4",
    },
    {
      id: "4",
      title: "جلسه ۱۴: میانگین و واریانس",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/14.mp4",
    },
    {
      id: "5",
      title: "جلسه ۱۵: آشنایی با اکتاو/متلب",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/15.mp4",
    },
    {
      id: "6",
      title: "جلسه ۱۶: خواص امید ریاضی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/16.mp4",
    },
    {
      id: "7",
      title: "جلسه ۱۷: نامساوی مارکف و بینه",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/17.mp4",
    },
    {
      id: "8",
      title: "جلسه ۱۸: واریانس",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/18.mp4",
    },
    {
      id: "9",
      title: "جلسه ۱۹: توزیع یکنواخت و توزیع گوسی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/19.mp4",
    },
    {
      id: "10",
      title: "جلسه ۲۰: توزیع نمایی، رایلی و کوشی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/20.mp4",
    },
    {
      id: "1",
      title: "جلسه ۲۱: توزیع دوجمله‌ای، توزیع هندسی و تابعی از یک متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/21.mp4",
    },
    {
      id: "2",
      title: "جلسه ۲۲: ادامه تابعی از یک متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/22.mp4",
    },
    {
      id: "3",
      title: "جلسه ۲۳: قضیه اساسی امید ریاضی، تعریف گشتاور یک متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/23.mp4",
    },
    {
      id: "4",
      title: "جلسه ۲۴: تابع مولد گشتاور",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/24.mp4",
    },
    {
      id: "5",
      title: "جلسه ۲۵: تابع مشخصه",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/25.mp4",
    },
    {
      id: "6",
      title: "جلسه ۲۶: دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/26.mp4",
    },
    {
      id: "7",
      title: "جلسه ۲۷: ادامه دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/27.mp4",
    },
    {
      id: "8",
      title: "جلسه ۲۸: تابع چگالی احتمال مشترک",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/28.mp4",
    },
    {
      id: "9",
      title: "جلسه ۲۹: متغیرهای تصادفی مستقل",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/29.mp4",
    },
    {
      id: "10",
      title: "جلسه ۳۰: کواریانس و ضریب همبستگی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/30.mp4",
    },
    {
      id: "1",
      title:
        "جلسه ۳۱: نامساوی شوارتز، تابع مولد گشتاور مشترک، تابع مشخصه مشترک",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/31.mp4",
    },
    {
      id: "2",
      title: "جلسه ۳۲: ادامه تابع مشخصه مشترک",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/32.mp4",
    },
    {
      id: "3",
      title: "جلسه ۳۳: تابعی از دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/33.mp4",
    },
    {
      id: "4",
      title: "جلسه ۳۴: ادامه تابعی از دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/34.mp4",
    },
    {
      id: "5",
      title:
        "جلسه ۳۵: ادامه تابعی از دو متغیر تصادفی، تعریف متغیرهای مشترک نرمال",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/35.mp4",
    },
    {
      id: "6",
      title: "جلسه ۳۶: توزیع شرطی (قسمت اول)",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/36.mp4",
    },
    {
      id: "7",
      title: "جلسه ۳۷: توزیع شرطی (قسمت دوم)",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/37.mp4",
    },
    {
      id: "8",
      title: "جلسه ۳۸: توزیع شرطی (قسمت سوم)",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/38.mp4",
    },
    {
      id: "9",
      title: "جلسه ۳۹: کاربردی از توزیع شرطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/39.mp4",
    },
    {
      id: "10",
      title: "جلسه ۴۰: تخمین به‌عنوان کاربردی از توزیع شرطی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/40.mp4",
    },
    {
      id: "1",
      title:
        "جلسه ۴۱: دنباله‌ای از متغیرهای تصادفی، تابع چگالی احتمال چند‌متغیره",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/41.mp4",
    },
    {
      id: "2",
      title: "جلسه ۴۲: حل تمرین‌های مبحث دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/42.mp4",
    },
    {
      id: "3",
      title: "جلسه ۴۳: ادامه حل تمرین‌های مبحث دو متغیر تصادفی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/43.mp4",
    },
    {
      id: "4",
      title: "جلسه ۴۴: قضیه حد مرکزی",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/44.mp4",
    },
    {
      id: "5",
      title: "جلسه ۴۵: فاصله اطمینان",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/45.mp4",
    },
    {
      id: "6",
      title: "جلسه ۴۶: ادامه فاصله اطمینان + آزمون فرض",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/probability/46.mp4",
    },
  ],
};
