import { Course } from "@/types/Course";

export const signalsAndSystems: Course = {
  title: {
    fa: "سیگنال ها و سیستم ها",
    en: "signals-and-systems",
  },
  sources: [
    {
      id: "1-note",
      title: "جزوه کامل",
      type: "note",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/1-note.pdf",
    },
    {
      id: "1-1",
      title: "فصل اول - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/1-1.mp4",
    },
    {
      id: "1-2",
      title: "فصل اول - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/1-2.mp4",
    },
    {
      id: "1-3",
      title: "فصل اول - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/1-3.mp4",
    },
    {
      id: "1-4",
      title: "فصل اول - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/1-4.mp4",
    },
    {
      id: "2-1",
      title: "فصل دوم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/2-1.mp4",
    },
    {
      id: "2-2",
      title: "فصل دوم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/2-2.mp4",
    },
    {
      id: "2-3",
      title: "فصل دوم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/2-3.mp4",
    },
    {
      id: "2-4",
      title: "فصل دوم - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/2-4.mp4",
    },
    {
      id: "3-1",
      title: "فصل سوم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/3-1.mp4",
    },
    {
      id: "3-2",
      title: "فصل سوم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/3-2.mp4",
    },
    {
      id: "3-3",
      title: "فصل سوم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/3-3.mp4",
    },
    {
      id: "3-4",
      title: "فصل سوم - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/3-4.mp4",
    },
    {
      id: "4-1",
      title: "فصل چهارم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/4-1.mp4",
    },
    {
      id: "4-2",
      title: "فصل چهارم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/4-2.mp4",
    },
    {
      id: "4-3",
      title: "فصل چهارم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/4-3.mp4",
    },
    {
      id: "4-4",
      title: "فصل چهارم - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/4-4.mp4",
    },
    {
      id: "5-1",
      title: "فصل پنجم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/5-1.mp4",
    },
    {
      id: "5-2",
      title: "فصل پنجم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/5-2.mp4",
    },
    {
      id: "5-3",
      title: "فصل پنجم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/5-3.mp4",
    },
    {
      id: "5-4",
      title: "فصل پنجم - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/5-4.mp4",
    },
    {
      id: "8-1",
      title: "فصل هشتم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/8-1.mp4",
    },
    {
      id: "8-2",
      title: "فصل هشتم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/8-2.mp4",
    },
    {
      id: "8-3",
      title: "فصل هشتم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/8-3.mp4",
    },
    {
      id: "8-4",
      title: "فصل هشتم - جلسه چهارم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/8-4.mp4",
    },
    {
      id: "9-1",
      title: "فصل نهم - جلسه اول",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/9-1.mp4",
    },
    {
      id: "9-2",
      title: "فصل نهم - جلسه دوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/9-2.mp4",
    },
    {
      id: "9-3",
      title: "فصل نهم - جلسه سوم",
      type: "video",
      url: "https://nitacademy.s3.ir-thr-at1.arvanstorage.ir/signals-and-systems/9-3.mp4",
    },
  ],
};
